### ISSUE TITLE
Filtering on nested arrays

### ISSUE THREAD

**Issue by allenfuller** [loredanacirstea/meteor-tabular-filter#6]
Hi @loredanacirstea, I saw your note that you're not actively maintaining this project anymore, but after working with it this afternoon, I'm really impressed! Thank you for creating it.

One issue I've run into is using nested arrays from my schema. For instance:

```
// Primary schema for contacts
let contactSchema = new SimpleSchema({
  [ ... ],
  companies: {
    label: "Company",
    type: [ companySchema ]
  }
});

// sub-schema for companies/employers used in contactSchema
let companySchema = new SimpleSchema({
  company: {
    label: "Company",
    type: String,
    optional: true
  },
  jobTitle: {
    label: "Job Title",
    type: String,
    optional: true
  }
});
```

As of right now, if I try to filter by Company or Job Title, I get an error: `MinimongoError: Minimongo doesn't support $ operator in projections yet.`

So I'm thinking of kicking the `selector` over the to the server, or trying to at least limit those fields for the time being.

Any thoughts on how to enable filtering by nested arrays?

Thanks!

**Comment by loredanacirstea** [comment]
I've done a small change, so please test with the new version (0.1.5).
Also, have a look at https://github.com/loredanacirstea/meteor-tabular-filter#omit-schema-fields, for eliminating the first `Company` option with: 

```
 let contactSchema = new SimpleSchema({
  [ ... ],
  companies: {
   label: "Company",
   type: [ companySchema ],
   tabularFilterOmit: true
  }
});
```

**Comment by allenfuller** [comment]
Hi @loredanacirstea, I've tested the change this morning and it works perfectly! Thank you!
