### ISSUE TITLE
Make On Field as variable

### ISSUE THREAD

**Issue by ivan133** [loredanacirstea/meteor-tabular-filter#7]
I want to change text on the "On Field" dropdown, for instance use anti:i18n package.
As far as I see it is hardcoded in the template.

**Comment by loredanacirstea** [comment]
I published ver. 0.2.0

Changes:
`Session.set("schema", "Table");` is now: 
`Session.set("tabular-filter", {schema: "Table", label: 'On Field'});`, so you can have a custom label for the filter.

https://github.com/loredanacirstea/meteor-tabular-filter/commit/08e038d984b7959b82bf7e4e63624f24c3ad3ffe

**Comment by ivan133** [comment]
Oh thank you so much!
